version: 2
updates:
  - directory: /
    package-ecosystem: github-actions
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
  - directory: /
    package-ecosystem: bundler
    schedule:
      interval: weekly
    groups:
      ruby-minor-updates:
        patterns:
          - "*"
  
  - directory: /
    package-ecosystem: npm
    schedule:
      interval: weekly
    groups:
      npm-minor-updates:
        patterns:
          - "*"